### ISSUE TITLE
Stack trace during logging.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1197]
@frnkdny saw this during testing on v1.0.0-beta (@frnkdny can you confirm the version?)

```
2016-11-30 21:01:06.639 [INFO][27] calc_graph.go 260: Local endpoint updated id=WorkloadEndpoint(node=fd-kube-scale-008.c.unique-caldron-775.internal, orchestrator=k8s, workload=default.getter-yf3i3, name=eth0)
Traceback (most recent call last):
 File "logging/handlers.py", line 864, in emit
 File "site-packages/gevent/_socket2.py", line 420, in sendto
gaierror: [Errno -2] Name or service not known
Logged from file actor.py, line 359
```

**Comment by fasaxc** [comment]
@caseydavenport I tracked down the line in question.  That happens if it tries to log to syslog and it can't reach the (local) syslog server.  I believe the exception gets swallowed by the logging framework so it should be benign (apart from the lack of syslog output).

If it's having trouble reaching syslog, that's likely a container-related issue.  Should we simply be disabling syslog logging in container-land?  We normally log to screen in those environments and then let the orchestrator do what it wants with the logs.

Downgrading to P2 unless you're convinced it's not just a misconfig/log spam.

**Comment by caseydavenport** [comment]
Yeah, we were just setting LOGEVERITYSYS instead of SCREEN.  This is just a misconfig.
