### ISSUE TITLE
Felix writes lots of logs

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#1780]
## Current Behavior
Ran a 72 hour churn test on an Openstack 10-node rig (on GCE), adding and removing VMs every 30 seconds.  After 72 hours the rig was dead - the compute nodes disks were full.  

The major culprit was Felix: syslog was about 7G and `/var/log/calico/` had about 3G of logs in it.  Compare this to `/var/log/nova` which was 11M and `/var/log/neutron` which was 335M.  

Felix was in INFO logging mode (by default), not DEBUG.

I am seeing a `syslog.1` file and a `felix.log.1` file, so log rotation is being attempted at least.  I also see an empty `felix.log.1.gz` file - perhaps log rotation didn't have enough room left at the point it tried to zip the logs up?  

## Expected Behavior
I'd expect Felix to produce quantities of logs similar to other openstack components, not orders of magnitude more.

## Possible Solution
Perhaps set WARNING level by default?  Run log rotation more often?

**Comment by neiljerram** [comment]
My overall thoughts so far:

1. log rotation is certainly an option, but I think it's independent of us ensuring that our volume of logging is reasonable.  Also any particular log rotation approach/config would be a matter for the installer and out of Calico's scope.  That said, for a reference for what can be done with log rotation: https://linux.die.net/man/8/logrotate.

2. For both Felix and networking-calico, I think it's likely that our current volume of non-DEBUG logging, per endpoint, is way too large.  My gut feel is that non-DEBUG logging per endpoint should probably be just a handful of lines, and in current practice I guess that it's actually 10s to 100s of lines.

@fasaxc @lwr20 WDYT?  In particular about (2), and how much non-DEBUG logging is reasonable ?

@lwr20 Do you still have logs from your churn test, so that I can see in detail what our logging per-endpoint is now?

**Comment by fasaxc** [comment]
@neiljerram I grabbed a log bundle from one of my computes before tearing my rig down.  It's a tricky balance.  I do think we could make the dataplane a lot less chatty; a lot of that comes from reducing timers from minutes to seconds to work around iptables conflicts, for example.

**Comment by fasaxc** [comment]
>  Also any particular log rotation approach/config would be a matter for the installer and out of Calico's scope
I thought we shipped a logrotate config file in our deb/rpm?

**Comment by neiljerram** [comment]
This has now been substantially improved by #1806, so I'll close this issue now.
