### ISSUE TITLE
Some Felix etcd config options ignored when not setting DataStoreType in the same source.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#1796]
Datastore type defaults to etcdv3, but the Felix specific (not generic calicoapiconfig) suboptions get ignored silently (at all log levels) when it's not specified.

e.g. a Felix config file, or Felix environment variables setting etcd certificates are ignored, but the logs actually declare them being parsed successfully...

https://github.com/projectcalico/felix/blob/682bfdb4a26f45b7ef7628bbb925ee72edb3bfca/config/config_params.go#L368 is the culprit: it requires the datastore type to come from a Felix-specific source in order to consider other variables from those sources.

This took quite a long time to debug: the logging is not up to scratch given how complex the code is...

**Comment by neiljerram** [comment]
@matthewdupre @Brian-McM in the beginning, Felix was written in Python and there was no cross-component approach to config (such as we now have via libcalico-go). For configuring Felix's data store we supported FELIX_... environment variables and felix.cfg.

Then the common libcalico-go approach was added, which gives data store configuration by environment variables with CALICO_ prefix, or with no prefix at all. Felix calls LoadConfigFromEnvironment to initialize a CalicoAPIConfig object based on those possible variables.

So we wanted the common approach to work, and we also wanted existing setups to keep working if they were using FELIX_... or felix.cfg. That's why the code is as you currently see it.

**Comment by neiljerram** [comment]
The change in #2077 is definitely wrong because the default value of config.DatastoreType is "etcdv3". So, if you configure DATASTORE_TYPE=kubernetes, plus other common variables for KDD, this change will wrongly overwrite that by setting cfg.Spec.DatastoreType to etcdv3.

**Comment by neiljerram** [comment]
I think we definitely shouldn't change the logic here. There isn't an easy win on that front, and we shouldn't make an already tricky situation even trickier.

What *may* be worthwhile, though, is to improve our documentation about this, and/or emit warning logs that help people see and understand what's happening when FELIX_... or felix.cfg settings are ignored.

@Brian-McM WDYT?

**Comment by Brian-McM** [comment]
I'm declining that PR I made, I clearly had some misconceptions about how that configuration worked and looking at it again I see that doesn't fix anything. One way of fixing this issue though would be to not nest the "if" statements for the sub options under the check for the DatastoreType, and just overwrite the etcd options regardless of whether the DatastoreType is etcd or not. That way we can just say the old felix configuration options always overwrite the common ones, without special triggers.
