### ISSUE TITLE
linux/dataplane: rp_filter default value

### ISSUE THREAD

**Issue by lucab** [projectcalico/felix#2082]
Linux dataplane logic currently contains the following: https://github.com/projectcalico/felix/blob/56335941df75e6f88a4105cef2c0ab0902d2f588/dataplane/linux/int_dataplane.go#L999-L1000

However, starting with systemd v240, the default for systemd-based distributions is `rp_filter = 2`, see https://github.com/systemd/systemd/blob/v240/sysctl.d/50-default.conf#L24-L25.

**Comment by lucab** [comment]
This was originally reported against Fedora CoreOS at https://github.com/coreos/fedora-coreos-tracker/issues/219, but will likely start to affect more distros as soon as they embrace the newer systemd default.

**Comment by fasaxc** [comment]
That's not a great default they've set.  It prevents any interface from being set to "strict" policing.

**Comment by lucab** [comment]
Switch happened in https://github.com/systemd/systemd/pull/10971.

**Comment by NitinAtIntel** [comment]
Hello, does Calico have an update on this other than the existing choices of `rp_filter = 1` or `FELIX_IGNORELOOSERPF`?  Thanks

**Comment by fasaxc** [comment]
Those are our current recommendations.  The problem is that setting the global setting to loose means that we can't set individual interfaces to strict.  It's better to set the global setting to strict and then set loose on the interfaces that you are doing asymmetric routing over.

We might be able to swap out this check for an iptables rule, which is how we implement the RPF check for IPv6.  It needs some analysis though.
