### ISSUE TITLE
cannot change interface prefix

### ISSUE THREAD

**Issue by magicsong** [projectcalico/felix#2117]
## Expected Behavior
i want to use calico for policy only. all the weps should begin with custom value

## Current Behavior
the prefix of all weps is still `cali` 

## Steps to Reproduce (for bugs)

1. download policy-only-calico.yaml
2. add enviroment variable `FELIX_INTERFACEPREFIX=nic`to all deployment.
3. apply the yaml

## Context

We have a CNI in cloud provider and want to use calico for policy only

**Comment by tmjd** [comment]
I believe in policy-only mode Calico will not be responsible for creating the interface prefixes, I think that will be whatever CNI you are using. So you'll need to update your CNI config to have the actual interfaces be named differently.

**Comment by magicsong** [comment]
@tmjd when i type `iptbales -nvL` i can see some infos like `unknown interface calixxxxxxxx`, it will not affect the policy, is it right?

**Comment by tmjd** [comment]
Are you referring to lines like
`0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:zTj6P0TIgYvgz-md */ /* Unknown interface */`
That is not referring to a specific interface.
The `cali:zTj6P0TIgYvgz-md` is not an interface but a hash that is used to identify the rule.
That rule is for dropping traffic to or from unknown interfaces.

So that is an expected rule that Calico/Felix creates.

**Comment by magicsong** [comment]
@tmjd yes, it is. thanks for your explanation. I am so fortunate to learn some knowledge in this issue.

**Comment by tmjd** [comment]
I believe this issue is resolved so I'm going to close it.
