### ISSUE TITLE
Support CIDRs in failsafe inbound/outbound configuration

### ISSUE THREAD

**Issue by kgtw** [projectcalico/felix#2645]
Currently failsafe configurations allow specifying the protocol & port, this functionality should be expanded to include a CIDR for cases when it is more desired to restrict to specific ranges. 

## Expected Behavior

Allow specifying an optional CIDR with the protocol and port. 

```
- name: FELIX_FAILSAFEINBOUNDHOSTPORTS
   value: "172.20.10.0/24:tcp:22,172.20.10.0/24:tcp:5473,172.20.10.0/24:tcp:9098,172.20.10.0/24:tcp:9099,172.20.10.0/24:tcp:50051,172.20.10.0/24:tcp:8080,172.20.10.0/24:tcp:10250"
- name: FELIX_FAILSAFEOUTBOUNDHOSTPORTS
   value: "tcp:53,udp:53,172.20.10.0/24:tcp:5473,172.20.10.0/24:tcp:443,172.20.10.0/24:tcp:9099,172.20.10.0/24:tcp:50051,172.20.10.0/24:tcp:8080,172.20.10.0/24:tcp:80"
```

## Current Behavior

As an example we are running Calico in Kubernetes and configure the failsafe ports via environment variables.

```
- name: FELIX_FAILSAFEINBOUNDHOSTPORTS
   value: "tcp:22,tcp:5473,tcp:9098,tcp:9099,tcp:50051,tcp:8080,tcp:10250"
- name: FELIX_FAILSAFEOUTBOUNDHOSTPORTS
   value: "tcp:53,udp:53,tcp:5473,tcp:443,tcp:9099,tcp:50051,tcp:8080,tcp:80"
```

When these rules are applied, they are applied with a `0/0` CIDR.

## Possible Solution

I've had a quick search and I believe these are the main areas that will need updating.
- Support CIDRs in the `ProtoPort` struct: https://github.com/projectcalico/felix/blob/master/config/config_params.go#L332-L335
- Update parsing to handle CIDRs: https://github.com/projectcalico/felix/blob/master/config/param_types.go#L306-L343
- Update the failsafe in/out chain functions to render static rules with CIDR's from the `ProtoPort` struct: https://github.com/projectcalico/felix/blob/master/rules/static.go#L400-L464

**Comment by mgleung** [comment]
Hi @kgtw thanks for your PR! We always appreciate contributions. 

I think I want to understand your use case a bit more before we decide on if this is the right solution. What's the situation where you need to specify a specific CIDR as a failsafe? I think our intention was for that level of information to be configured via policies so I'm wondering what your use case is and if policies do not cover it?

**Comment by kgtw** [comment]
Hi @mgleung 

We are currently implementing calico host endpoint network policies in a PCI-DSS compliant environment for services within our Kubernetes cluster running as `hostNetwork: true`. As such we need to restrict ingress/egress as much as possible.

For example, if we have fail-safe inbound configured for `tcp:22` and we have good/bad policies applied for this, regardless of the policy the failsafe would allow that inbound traffic.

**Comment by mgleung** [comment]
So from my understanding, the main use case for the failsafes is so that while you're editing your policies, you don't accidentally lock yourself out of an endpoint when a default deny is called (in the absence of any policies, all traffic is denied to the endpoint). In this way, the fail safes really only provide access in very specific cases. I'm worried that allowing CIDRs in starts letting us configure larger security holes since now you'll have to check what's configured in the failsafes as well as what is configured by your policies in order to tell how traffic is supposed to behave and now that they are configured in multiple places, it is possible to  miss something and leave access to things that were not intended.

Based on your use case, it sounds like you're looking to ensure that communication is allowed to specific workloads. Have you tried writing a policy with a higher priority than all of your other policies that will allow this? Then that policy will allow you to access what you need to and if any conflicting policy is written later, as long as it is a lower priority, it will defer to your other policy and communications will not be cut off.

**Comment by mgleung** [comment]
Hey @kgtw, sorry, I missed the case where we might cut off access to the datastore (which invalidates any fixes we would make through network policy). I think I understand the use cases that this will cover. I'll review the PR and let's see if we can get this in. Thanks and sorry for the delay.
