### ISSUE TITLE
Is there a way to preferentially choose etcd config over the felix.cfg global options?

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/felix#804]
In calico-docker, we allow the user to dynamically change the log levels by changing the global config values in etcd.

It would be nice to specify default options in the felix.cfg config file that could be overridden by the values in etcd.  Is this possible?

This would allow us to ensure we log to screen and not to file immediately (to capture start up logs) - and then use the values in etcd to toggle the values dynamically.  Last time I tinkered in this area, it seemed that the felix.cfg options took precedence over the values in etcd.

**Comment by fasaxc** [comment]
@plwhite I think we've got the order of our config wrong, preventing calicoctl from being able to disable file logging early on but then enable it dynamically later.  Should we just swap it around so that per-host etcd config overrides file/env vars?

Alternatively, we could split felix.cfg into `[default]` and `[override]` sections that come before/after the others then rob could use the `[default]` section to enable screen logging and disable file logging but it would still get overridden by etcd?

**Comment by plwhite** [comment]
Etcd configuration does override file / env vars. Doesn't it?

**Comment by fasaxc** [comment]
Is this still a WIBNI?

**Comment by fasaxc** [comment]
Original reason for needing the override will be fixed by #1157.
