### ISSUE TITLE
Move to etcd v3 API

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#952]
This umbrella issue tracks moving to the etcd v3 API.  At the time of writing, that API is not yet released.

The v3 API is gRPC based and allows for push from the server, removing the requirement for felix to issue a new poll after each response.  That should be a huge scalability win.  However, the structure of the API is quite different and incompatible with the v2 API (no directories, leases instead of TTLs, binary keyspace).  Overall, those changes are well-aligned with what we want but we'll have a lot of work to do:

...removed out of date checklist...

**Comment by plwhite** [comment]
My thoughts on the migration are that it's hard (well, duh).

* A v2 over v3 layer allowing us to use clients unmodified would make some of the dull client stuff easier.
* We have lots of proxies. It would be better if we didn't have to reinstall them all.
* Finally, Felix really needs the right version, since the watch API changes. Somehow we need to tell all the Felixes which version to use - which if we have to do a full root and branch upgrade means talking to etcd, finding the version is now v3, and then loading the v3 API code. That's tricky.

The model of "stop everything, upgrade everything, restart everything" is horrible, but I haven't come up with a good model for how to do anything better.

**Comment by plwhite** [comment]
The etcd guys have said what they are planning, and it's a relatively simple solution.

* There will be a v2 API, with a v2 data store behind it.
* There will be a v3 API, with a v3 data store behind it.

The same etcd instance will support both APIs, but the data stores are disjoint. That means that the simplest way to make this all work is that : 

* Everybody (all clients) use the v2 API
* The migration process sets a flag to make the data store read only.
* The migration process copies the content of the v2 data store to the v3 data store.
* The migration process sets a flag to report that the v3 data store is now live.

A more refined and less shaky version of this is : 

* Everybody (all clients) use the v2 API.
* The migration process starts migration. It : 
    * Watches for changes to the v2 data
    * Copies the content of the v2 data store to the v3 data store, allowing for changes that happen under its feet.
    * Sets a flag to tell clients that the v3 store is now the master, and the v2 store is no longer in use.
    * For a short time (maybe a second or two), monitors the v2 store for clients writing to the wrong place.

This isn't particularly easy - we might want to do something simple in the first instance and only do the more complex versions if we absolutely have to (which would depend on the scale of the deployments).

**Comment by lxpollitt** [comment]
Given we have to write the translate function, we should also evaluate whether we want to make any changes do our data model as part of this transition.

**Comment by fasaxc** [comment]
@tomdee I think you're working with someone to implement this?

**Comment by fasaxc** [comment]
Enabling work is going on under https://github.com/projectcalico/libcalico-go/pull/336

**Comment by fasaxc** [comment]
etcdv3 support was a flagship feature of the Calico v3.0.0 release
