### ISSUE TITLE
Mirantis Fuel 7/ unable to run apt-get install python-pip

### ISSUE THREAD

**Issue by linuxsimba** [projectcalico/felix#985]
Setup Mirantis Fuel 7 to be an apt-cacher.  Installed the calico plugin from github, not from the mirantis website. The one on the Mirantis website is old. After doing this, ``apt-get install python-pip`` in the ``calico-controller.sh`` script fails to run.  Changing it to ``easy_install pip`` fixes the problem for me.
Looks like the apt-cacher doesn't include that component.  Python-pip resides in 'universe' component.

**Comment by neiljerram** [comment]
Thanks @linuxsimba for reporting this.  I see two overall problems here:
- Our install scripts don't work with the Fuel master as an APT cacher; instead they require external access.
- The Calico plugin on the Mirantis website needs updating.

We're going through Fuel 7 certification at the moment, so that will address the second point.  Current ETA for that is March/April.

The first point will require longer term work, and I don't think we'll address it for our Fuel 7 plugin.  After the `easy_install pip` change that you mentioned, I would still expect later installs in the script to go wrong - is that what you observed?

**Comment by skamithi** [comment]
calico plugin installed with no problem under 2 conditions
* external connectivity to openstack nodes because calico plugin repo are not cached by fuel apt-cacher.
* ``easy_install pip`` instead of ``apt-get install python-pip`` because I was using the apt-cacher. 

Even without the "easy_install pip" change, the only portion of the bash script ``calico_controller.sh`` that failed was minor. Not sure what "pyinotify" and "pyaml" do. I saw no recognizable change in the behaviour of the setup with this minor failure.

**Comment by neiljerram** [comment]
Moved to https://bugs.launchpad.net/fuel-plugin-calico/+bug/1629305
